version: '2'

services:

  unittest:
    image: maven:3.3.9-jdk-8
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    command: bash -c "cd /app && mvn verify -B -q"

  integration-tests:
    build:
      context: .
      dockerfile: integration-tests.Dockerfile
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    command: bash -c "cd /app && mvn verify -B -q -Pintegration-tests"
    links:
      - app
      - rabbitmq
      - redis

  acceptance-tests:
    build:
      context: .
      dockerfile: acceptance-tests.Dockerfile
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    command: bash -c "cd /app && mvn verify -B -q -Pacceptance-tests"
    links:
      - app

  app:
    extends:
      file: docker-compose.yml
      service: app
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis
    links:
      - redis
      - rabbitmq

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq